spring.application.name=almacen

spring.datasource.url=jdbc:mysql://localhost:3306/sesesp_almacen
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true