spring.application.name=almacen

spring.datasource.url=jdbc:mysql://localhost:3306/almacen_v5
spring.datasource.username=root
spring.datasource.password=

# validate: verifica que la BD coincide con las entities pero no modifica nada
# Cambia a update solo en desarrollo si quieres que Hibernate ajuste columnas
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

debug = true